### ISSUE TITLE
Cow as loading symbol

### ISSUE THREAD

**Issue by BullshitPingu** [mobileappdevhm/team2#33]
We need a cow as loading symbol

**Comment by hmkrivoj** [comment]
`I/flutter (23307): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (23307): The following assertion was thrown while finalizing the widget tree:
I/flutter (23307): _AnimatedImageState#37286(tickers: tracking 1 ticker) was disposed with an active Ticker.
I/flutter (23307): _AnimatedImageState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was
I/flutter (23307): called on the mixin, that Ticker was still active. All Tickers must be disposed before calling
I/flutter (23307): super.dispose(). Tickers used by AnimationControllers should be disposed by calling dispose() on the
I/flutter (23307): AnimationController itself. Otherwise, the ticker will leak.
I/flutter (23307): The offending ticker was: _WidgetTicker(created by _AnimatedImageState#37286(lifecycle state:
I/flutter (23307): created, no widget, not mounted, tickers: tracking 0 tickers))
I/flutter (23307): The stack trace when the _WidgetTicker was actually created was:
I/flutter (23307): #0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:64:40)
I/flutter (23307): #1      new Ticker (package:flutter/src/scheduler/ticker.dart:66:6)
I/flutter (23307): #2      new _WidgetTicker (package:flutter/src/widgets/ticker_provider.dart)
I/flutter (23307): #3      __AnimatedImageState&State&TickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:170:38)
I/flutter (23307): #4      new AnimationController (package:flutter/src/animation/animation_controller.dart:129:21)
I/flutter (23307): #5      new _AnimatedImageState (package:courses_in_english/ui/animation/animated_image.dart:51:23)
I/flutter (23307): #6      AnimatedImage.createState (package:courses_in_english/ui/animation/animated_image.dart:27:46)
I/flutter (23307): #7      new StatefulElement (package:flutter/src/widgets/framework.dart:3710:23)
I/flutter (23307): #8      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:789:42)
I/flutter (23307): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2905:40)
I/flutter (23307): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (23307): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (23307): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (23307): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (23307): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (23307): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (23307): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (23307): #17     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter (23307): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (23307): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (23307): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (23307): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
I/flutter (23307): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (23307): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (23307): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (23307): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (23307): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (23307): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (23307): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (23307): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (23307): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (23307): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (23307): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (23307): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (23307): #34     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3955:11)
I/flutter (23307): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (23307): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (23307): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
I/flutter (23307): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
I/flutter (23307): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
I/flutter (23307): #40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
I/flutter (23307): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
I/flutter (23307): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
I/flutter (23307): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
I/flutter (23307): #44     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:744:36)
I/flutter (23307): #45     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:729:20)
I/flutter (23307): #46     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2222:19)
I/flutter (23307): #47     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:722:11)
I/flutter (23307): #48     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:254:23)
I/flutter (23307): #49     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1666:58)
I/flutter (23307): #50     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:740:15)
I/flutter (23307): #51     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1666:13)
I/flutter (23307): #52     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:243:5)
I/flutter (23307): #53     RenderSliverMultiBoxAdaptor.insertAndLayoutLeadingChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:352:5)
I/flutter (23307): #54     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:184:31)
I/flutter (23307): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (23307): #56     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:336:13)
I/flutter (23307): #57     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1131:12)
I/flutter (23307): #58     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1049:20)
I/flutter (23307): #59     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter (23307): #60     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
I/flutter (23307): #61     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter (23307): #62     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter (23307): #63     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (23307): #64     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (23307): #65     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (23307): #66     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (23307): #67     _invoke (dart:ui/hooks.dart:120:13)
I/flutter (23307): #68     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter (23307): 
I/flutter (23307): When the exception was thrown, this was the stack:
I/flutter (23307): #0      __AnimatedImageState&State&TickerProviderStateMixin.dispose.<anonymous closure> (package:flutter/src/widgets/ticker_provider.dart:187:13)
I/flutter (23307): #1      __AnimatedImageState&State&TickerProviderStateMixin.dispose (package:flutter/src/widgets/ticker_provider.dart:200:6)
I/flutter (23307): #2      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:3821:12)
I/flutter (23307): #3      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1697:13)
I/flutter (23307): #4      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
I/flutter (23307): #5      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4642:14)
I/flutter (23307): #6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1693:13)
I/flutter (23307): #7      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
I/flutter (23307): #8      _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1706:25)
I/flutter (23307): #9      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2328:27)
I/flutter (23307): #10     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2160:15)
I/flutter (23307): #11     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2327:7)
I/flutter (23307): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:628:18)
I/flutter (23307): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (23307): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (23307): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (23307): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (23307): #17     _invoke (dart:ui/hooks.dart:120:13)
I/flutter (23307): #18     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter (23307): ════════════════════════════════════════════════════════════════════════════════════════════════════
E/flutter (23307): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (23307): setState() called after dispose(): TimetableState#dcaeb(lifecycle state: defunct, not mounted)
E/flutter (23307): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback. The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (23307): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (23307): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1098:9)
E/flutter (23307): #1      State.setState (package:flutter/src/widgets/framework.dart:1124:6)
E/flutter (23307): #2      TimetableState.build.<anonymous closure> (package:courses_in_english/ui/screens/timetable_screen.dart:28:9)
E/flutter (23307): #3      _RootZone.runUnary (dart:async/zone.dart:1381:54)
E/flutter (23307): #4      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (23307): #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
E/flutter (23307): #6      Future._propagateToListeners (dart:async/future_impl.dart:662:32)
E/flutter (23307): #7      Future._complete (dart:async/future_impl.dart:467:7)
E/flutter (23307): #8      new Future.delayed.<anonymous closure> (dart:async/future.dart:310:16)
E/flutter (23307): #9      Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
E/flutter (23307): #10     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
E/flutter (23307): #11     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
E/flutter (23307): #12     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
E/flutter (23307): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (23307): setState() called after dispose(): TimetableState#dcaeb(lifecycle state: defunct, not mounted)
E/flutter (23307): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback. The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (23307): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (23307): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1098:9)
E/flutter (23307): #1      State.setState (package:flutter/src/widgets/framework.dart:1124:6)
E/flutter (23307): #2      TimetableState.build.<anonymous closure> (package:courses_in_english/ui/screens/timetable_screen.dart:28:9)
E/flutter (23307): #3      _RootZone.runUnary (dart:async/zone.dart:1381:54)
E/flutter (23307): #4      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (23307): #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
E/flutter (23307): #6      Future._propagateToListeners (dart:async/future_impl.dart:662:32)
E/flutter (23307): #7      Future._complete (dart:async/future_impl.dart:467:7)
E/flutter (23307): #8      new Future.delayed.<anonymous closure> (dart:async/future.dart:310:16)
E/flutter (23307): #9      Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
E/flutter (23307): #10     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
E/flutter (23307): #11     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
E/flutter (23307): #12     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
`

**Comment by BullshitPingu** [comment]
Should be fixed with: https://github.com/mobileappdevhm/team2/pull/58

**Comment by hmkrivoj** [comment]
No it isn't
`I/Choreographer(25381): Skipped 55 frames!  The application may be doing too much work on its main thread.
I/FlutterActivityDelegate(25381): onResume setting current activity to this
Restarted app in 3.421ms.
E/flutter (25381): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (25381): setState() called after dispose(): TimetableState#5c1e5(lifecycle state: defunct, not mounted)
E/flutter (25381): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback. The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (25381): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (25381): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1098:9)
E/flutter (25381): #1      State.setState (package:flutter/src/widgets/framework.dart:1124:6)
E/flutter (25381): #2      TimetableState.build.<anonymous closure> (package:courses_in_english/ui/screens/timetable_screen.dart:28:9)
E/flutter (25381): #3      _RootZone.runUnary (dart:async/zone.dart:1381:54)
E/flutter (25381): #4      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (25381): #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
E/flutter (25381): #6      Future._propagateToListeners (dart:async/future_impl.dart:662:32)
E/flutter (25381): #7      Future._complete (dart:async/future_impl.dart:467:7)
E/flutter (25381): #8      new Future.delayed.<anonymous closure> (dart:async/future.dart:310:16)
E/flutter (25381): #9      Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
E/flutter (25381): #10     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
E/flutter (25381): #11     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
E/flutter (25381): #12     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
E/flutter (25381): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (25381): setState() called after dispose(): TimetableState#5c1e5(lifecycle state: defunct, not mounted)
E/flutter (25381): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback. The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (25381): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (25381): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1098:9)
E/flutter (25381): #1      State.setState (package:flutter/src/widgets/framework.dart:1124:6)
E/flutter (25381): #2      TimetableState.build.<anonymous closure> (package:courses_in_english/ui/screens/timetable_screen.dart:28:9)
E/flutter (25381): #3      _RootZone.runUnary (dart:async/zone.dart:1381:54)
E/flutter (25381): #4      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (25381): #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
E/flutter (25381): #6      Future._propagateToListeners (dart:async/future_impl.dart:662:32)
E/flutter (25381): #7      Future._complete (dart:async/future_impl.dart:467:7)
E/flutter (25381): #8      new Future.delayed.<anonymous closure> (dart:async/future.dart:310:16)
E/flutter (25381): #9      Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
E/flutter (25381): #10     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
E/flutter (25381): #11     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
E/flutter (25381): #12     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
`
